const API_URL = "http://localhost:5000/api/incidents";

const form = document.getElementById("incidentForm");
const incidentTable = document.getElementById("incidentTable");
const activityFeed = document.getElementById("activityFeed");


const role =
localStorage.getItem("role");
 /** const role = localStorage.getItem("role");

const exportBtn =
document.getElementById("exportBtn");


if(exportBtn && role !== "admin"){

    exportBtn.style.display = "none";

}
alert("Role = " + localStorage.getItem("role")); **/

let incidentChart;
let failureChart;

/* =========================
   LOAD INCIDENTS
========================= */

async function loadIncidents() {

    try {

        const response =
        await fetch(API_URL);

        const data =
        await response.json();

        updateDashboard(data);

        const role = localStorage.getItem("role");

        renderTable(data);

        renderIncidentChart(data);

        renderFailureChart();

    }
    catch(error){

        console.error(error);

    }

}

async function downloadPDF(){

    const { jsPDF } = window.jspdf;

    const doc = new jsPDF();

    const response =
    await fetch(API_URL);

    const incidents =
    await response.json();

    const total =
    incidents.length;

    const high =
    incidents.filter(
    i => i.severity === "High"
    ).length;

    const medium =
    incidents.filter(
    i => i.severity === "Medium"
    ).length;

    const low =
    incidents.filter(
    i => i.severity === "Low"
    ).length;

    const pending =
    incidents.filter(
    i => i.status === "Pending"
    ).length;

    const inProgress =
    incidents.filter(
    i => i.status === "In Progress"
    ).length;

    const resolved =
    incidents.filter(
    i => i.status === "Resolved"
    ).length;

    // HEADER

    doc.setFontSize(20);
    doc.setFont("helvetica","bold");

    doc.text(
    "ERAFTS",
    20,
    20
    );

    doc.setFontSize(11);

    doc.text(
    "Emergency Response Analytics & Failure Tracking System",
    20,
    28
    );

    doc.line(
    20,
    32,
    190,
    32
    );

    // REPORT INFO

    doc.setFontSize(10);

    doc.text(
    `Report Date: ${new Date().toLocaleDateString()}`,
    20,
    42
    );

    doc.text(
    "Generated By: Administrator",
    20,
    48
    );

    doc.text(
    "System Status: Online",
    20,
    54
    );

    // EXECUTIVE SUMMARY

    doc.setFontSize(14);
    doc.setFont("helvetica","bold");

    doc.text(
    "1. Executive Summary",
    20,
    70
    );

    doc.setFontSize(10);
    doc.setFont("helvetica","normal");

    doc.text(
    `Total Incidents : ${total}`,
    25,
    80
    );

    doc.text(
    `High Risk : ${high}`,
    25,
    87
    );

    doc.text(
    `Medium Risk : ${medium}`,
    25,
    94
    );

    doc.text(
    `Low Risk : ${low}`,
    25,
    101
    );

    doc.text(
    `Pending : ${pending}`,
    100,
    80
    );

    doc.text(
    `In Progress : ${inProgress}`,
    100,
    87
    );

    doc.text(
    `Resolved : ${resolved}`,
    100,
    94
    );

    // INCIDENT TABLE

    doc.setFontSize(14);
    doc.setFont("helvetica","bold");

    doc.text(
    "2. Incident Details",
    20,
    120
    );

    let y = 130;

    doc.setFontSize(10);

    doc.text(
    "ID",
    20,
    y
    );

    doc.text(
    "Type",
    40,
    y
    );

    doc.text(
    "Location",
    80,
    y
    );

    doc.text(
    "Severity",
    130,
    y
    );

    doc.text(
    "Status",
    165,
    y
    );

    y += 8;

    incidents.forEach(
    incident => {

        doc.text(
        String(incident.id),
        20,
        y
        );

        doc.text(
        incident.emergency_type,
        40,
        y
        );

        doc.text(
        incident.location_zone,
        80,
        y
        );

        doc.text(
        incident.severity,
        130,
        y
        );

        doc.text(
        incident.status,
        165,
        y
        );

        y += 8;

    });

    // ANALYSIS

    y += 10;

    doc.setFontSize(14);
    doc.setFont("helvetica","bold");

    doc.text(
    "3. Conclusion",
    20,
    y
    );

    y += 10;

    doc.setFontSize(10);
    doc.setFont("helvetica","normal");

    doc.text(
    "The ERAFTS platform provides incident monitoring,",
    20,
    y
    );

    y += 6;

    doc.text(
    "tracking, analytics, and emergency response support.",
    20,
    y
    );

    y += 6;

    doc.text(
    "This report was generated automatically from",
    20,
    y
    );

    y += 6;

    doc.text(
    "the ERAFTS Emergency Operations Center.",
    20,
    y
    );

    // FOOTER

    doc.setFontSize(8);

    doc.text(
    "ERAFTS Emergency Operations Center | Confidential",
    20,
    285
    );

    doc.save(
    "ERAFTS_Incident_Report.pdf"
    );

}

async function editIncident(id){

    const newStatus =
    prompt(
    "Enter Status:\nPending\nIn Progress\nResolved"
    );

    if(!newStatus) return;

    await fetch(
    `${API_URL}/${id}`,
    {
        method:"PUT",

        headers:{
            "Content-Type":
            "application/json"
        },

        body:JSON.stringify({
            status:newStatus
        })
    });

    loadIncidents();
}

/* =========================
   KPI CARDS
========================= */

function updateDashboard(data){

    const high =
    data.filter(
    i => i.severity === "High"
    ).length;

    const medium =
    data.filter(
    i => i.severity === "Medium"
    ).length;

    const low =
    data.filter(
    i => i.severity === "Low"
    ).length;

    document.getElementById(
    "totalCount"
    ).innerText = data.length;

    document.getElementById(
    "highCount"
    ).innerText = high;

    document.getElementById(
    "mediumCount"
    ).innerText = medium;

    document.getElementById(
    "lowCount"
    ).innerText = low;

}

/* =========================
   INCIDENT TABLE
========================= */

function renderTable(data){

    incidentTable.innerHTML = "";

    data.forEach(incident => {

        const badgeClass =
(incident.severity || "Low").toLowerCase();

        incidentTable.innerHTML += `

        <tr>

            <td>
                ${incident.id}
            </td>

            <td>
                ${getIcon(
                incident.emergency_type
                )}

                ${incident.emergency_type}
            </td>

            <td>
                ${incident.location_zone}
            </td>

            <td>

                <span class="
                badge
                ${badgeClass}
                ">

               ${incident.severity || "Low"}

                </span>

            </td>

           <td>
    <span class="
    status
    ${incident.status
    .replace(/\s/g,'')
    .toLowerCase()}
    ">
    ${incident.status}
    </span>
</td> 

<td>

${
role === "admin"
?

`<button
onclick="editIncident(${incident.id})"
class="edit-btn">

✏ Edit

</button>

<button
onclick="deleteIncident(${incident.id})"
class="delete-btn">

🗑 Delete

</button>`

:

""

}

</td>

        </tr>

        `;

    });

}

/* =========================
   CREATE INCIDENT
========================= */

form.addEventListener(
"submit",
async (e)=>{

    e.preventDefault();

    const emergency_type =
    document.getElementById(
    "emergency_type"
    ).value;

    const location_zone =
    document.getElementById(
    "location_zone"
    ).value;

    const severity =
    document.getElementById(
    "severity"
    ).value;

    const status =
document.getElementById(
"status"
).value;

    const response =
    await fetch(API_URL,{

        method:"POST",

        headers:{
            "Content-Type":
            "application/json"
        },

        body:JSON.stringify({

            emergency_type,
            location_zone,
            severity,
            status

        })

    });

    if(response.ok){

        addActivity(
        `${emergency_type}
        incident reported`
        );

        form.reset();

        loadIncidents();

    }

});

/* =========================
   SEARCH
========================= */

document
.getElementById(
"searchInput"
)
.addEventListener(
"keyup",
function(){

    const value =
    this.value.toLowerCase();

    const rows =
    document.querySelectorAll(
    "#incidentTable tr"
    );

    rows.forEach(row=>{

        if(
            row.innerText
            .toLowerCase()
            .includes(value)
        ){

            row.style.display = "";

        }
        else{

            row.style.display = "none";

        }

    });

});

/* =========================
   INCIDENT CHART
========================= */

function renderIncidentChart(data){

    const medical =
    data.filter(
    i=>i.emergency_type==="Medical"
    ).length;

    const fire =
    data.filter(
    i=>i.emergency_type==="Fire"
    ).length;

    const flood =
    data.filter(
    i=>i.emergency_type==="Flood"
    ).length;

    const accident =
    data.filter(
    i=>i.emergency_type==="Accident"
    ).length;

    const ctx =
    document.getElementById(
    "incidentChart"
    );

    if(incidentChart){

        incidentChart.destroy();

    }

    incidentChart =
    new Chart(ctx,{

        type:"doughnut",

        data:{

            labels:[
                "Medical",
                "Fire",
                "Flood",
                "Accident"
            ],

            datasets:[{

                data:[
                    medical,
                    fire,
                    flood,
                    accident
                ],

                backgroundColor:[

                    "#3b82f6",
                    "#ef4444",
                    "#06b6d4",
                    "#f59e0b"

                ]

            }]

        }

    });

}

/* =========================
   FAILURE CHART
========================= */

function renderFailureChart(){

    const ctx =
    document.getElementById(
    "failureChart"
    );

    if(failureChart){

        failureChart.destroy();

    }

    failureChart =
    new Chart(ctx,{

        type:"bar",

        data:{

            labels:[

                "Communication",
                "Wrong Location",
                "Resource Shortage",
                "Coordination Gap"

            ],

            datasets:[{

                label:
                "Failure Causes",

                data:[
                    15,
                    10,
                    8,
                    5
                ],

                backgroundColor:
                "#ef4444"

            }]

        },

        options:{

            indexAxis:"y",

            responsive:true,

            plugins:{

                legend:{
                    display:false
                }

            }

        }

    });

}

/* =========================
   ACTIVITY FEED
========================= */

function addActivity(message){

    const now =
    new Date()
    .toLocaleTimeString();

    const p =
    document.createElement("p");

    p.innerHTML =

    `🟢 ${message}
    <br>
    <small>${now}</small>`;

    activityFeed.prepend(p);

}

/* =========================
   ICONS
========================= */

function getIcon(type){

    switch(type){

        case "Medical":
            return "⛨";

        case "Fire":
            return "🔥";

        case "Flood":
            return "🌊";

        case "Accident":
            return "🚔";

        default:
            return "🚨";

    }

}

/* =========================
   SIDEBAR NAVIGATION
========================= */

function showPage(page, element){

    const pages = [
        "dashboard",
        "incidents",
        "analytics",
        "settings"
    ];

    pages.forEach(id => {

        const section =
        document.getElementById(id);

        if(section){
            section.style.display = "none";
        }

    });

    const selectedPage =
    document.getElementById(page);

    if(selectedPage){
        selectedPage.style.display = "block";
    }

    document
    .querySelectorAll(".menu li")
    .forEach(item => {
        item.classList.remove("active");
    });

    if(element){
        element.classList.add("active");
    }
}


/* =========================
   INITIAL LOAD
========================= */

loadIncidents();

window.onload = function(){

    document.getElementById(
    "dashboard"
    ).style.display = "block";

    const role =
    localStorage.getItem("role");

    const exportBtn =
    document.getElementById("exportBtn");

    if(exportBtn && role !== "admin"){

        exportBtn.style.display = "none";

    }

    console.log("Current Role:", role);

}


/* =========================
   LIVE MAP
========================= */

const mapElement =
document.getElementById("map");

if(mapElement){

const map = L.map('map').setView(
    [8.5241,76.9366],
    12
);

L.tileLayer(
'https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',
{
 attribution:'© OpenStreetMap'
}
).addTo(map);

L.marker([8.5241,76.9366])
.addTo(map)
.bindPopup('🚑 Medical Emergency');



L.marker([8.5341,76.9466])
.addTo(map)
.bindPopup(
'🔥 Fire Incident'
);

L.marker([8.5141,76.9266])
.addTo(map)
.bindPopup(
'🌊 Flood Alert'
);

}



setInterval(() => {
    loadIncidents();
}, 5000);

